### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'add_noise_prob'

### ISSUE THREAD

**Issue by jmrichardson** [IBCNServices/GENDIS#17]
Hi, I am getting this error when running this code:

```
from gendis.genetic import GeneticExtractor
genetic_extractor = GeneticExtractor(population_size=50, iterations=25, verbose=False,
                                     normed=False, add_noise_prob=0.3, add_shapelet_prob=0.3,
                                     wait=10, plot='notebook', remove_shapelet_prob=0.3,
                                     crossover_prob=0.66, n_jobs=4, max_len=len(X_train_pyts) // 2)
```

Traceback (most recent call last):
  File "C:\Users\john\AppData\Roaming\Python\Python37\site-packages\IPython\core\interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-b1656543eab4>", line 5, in <module>
    crossover_prob=0.66, n_jobs=4, max_len=len(X_train_pyts) // 2)
TypeError: __init__() got an unexpected keyword argument 'add_noise_prob'

I installed by clone method.  Thanks for the help

**Comment by GillesVandewiele** [comment]
Hi @jmrichardson 

Sorry for my late reply, I was on holidays. It seems like the documentation is outdated and that some of the keywords have been renamed, my apologies for that. You can find the latest version of the constructor here: https://github.com/IBCNServices/GENDIS/blob/master/gendis/genetic.py#L143

I will update the documentation in the nearby future!

Let me know if you have any further issues.

**Comment by jmrichardson** [comment]
Thank you and appreciate the work here.  Will let you know if I run into any issues.  Thanks again
